key: your key
kaomoji:
    - ˊ_>ˋ
    - <(=﹁"﹁=)>
    - <(=￣Д￣)
    - (ノˊ_>ˋ)ノ┻━┻
    - <(ノ=﹁"﹁=)ノ┻━┻
    - ─=≡Σ((( つ•̀ω•́)つ
    - (｡・`ω´･)
    - (´・ω・`)
    - (`・ω・´)
    - ⊂彡☆))д`)
    - (￣ε(#￣)☆╰╮(￣▽￣///)
    - ( *・ω・)✄╰ひ╯
    - Σ( ° △ °|||)
    - (σ≧∀≦)σ
    - '| ω・´)'
    - ( ,,´･ω･)ﾉ"(´っω･｀｡)
    - _(:з」∠)_
    - _(눈_ 눈」∠)_
    - o(*≧▽≦)ツ
    - ≖‿≖✧
    - ( • ̀ω•́ )✧
    - (╯‵□′)╯︵┻━┻
    - ∑(っ °Д °;)っ
    - (ノ｀Д´)ノ┻━┻
    - (・∀・)
    - (・_・)
    - (つд⊂)
    - (*/ω＼*)
    - ⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄
    - (●´∀`●）
    - ヾ(❀╹◡╹)ﾉ~
    - (◕ω＜)☆
    - ~\(≥▽≤)/~
    - \*罒▽罒\*
    - ´∀`
    - o(*≥▽≤)ツ┏━┓
    - (｡ゝω・｡)ゞ
    - ≧ω≦
    - ≧▽≦
    - ＞ω＜
    - ＞﹏＜
    - ≧﹏≦
    - ≧△≦
